services:
  - type: web
    name: myanmar-explorer-api
    env: python
    region: singapore
    plan: free
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: ORIGIN
        value: https://myanmar-explorer.onrender.com
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
    healthCheckPath: /
